print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock Knock.')
input()
print('Who\'s there?')
input()
print('Interrepting cow.')
input()
print('Interrupting cow wh', end='')
print()
print('MOO!')